#  Build Angular App
FROM node:20 AS build

WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install -g @angular/cli && npm install

# Copia o restante do projeto
COPY . .

# Compila o app para produção
RUN ng build --configuration production

# Servir com NGINX
FROM nginx:stable-alpine

# Remove configuração padrão do NGINX
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos gerados do Angular (da etapa anterior)
COPY --from=build /app/dist/workplace-frontend/browser /usr/share/nginx/html

# Copia arquivo customizado de configuração (para redirecionamentos Angular)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expõe a porta 4200
EXPOSE 4200

# Inicia o servidor
CMD ["nginx", "-g", "daemon off;"]
